// Start date of alpha program
const START_DATE = new Date("2020-11-24T17:00:00.000");
const DAYS_IN_WEEK = 7;
export default {
    // return the current datetime
    getDate() {
        const now = new Date();
        return now;
    },

    // Param: now as a date object, generated by getDate()
    // return whether the stimulation can be on, available window = 5pm - 5am
    stimulationStatus(now) {
        const daysFromStart = now - START_DATE / 604800000;
        console.log(now - START_DATE);
        // second week of the program
        if (daysFromStart > DAYS_IN_WEEK && daysFromStart > DAYS_IN_WEEK < 2 * DAYS_IN_WEEK) { 
            // 5pm to 5am of the users' timezone
            if (now.getHours() > 17 || now.getHours() < 5) {
                return true;
            }
        }
        return false;
    },
};